### ISSUE TITLE
Regular expression

### ISSUE THREAD

**Issue by jzell** [HeidelTime/heideltime#27]
```
Hi,

I would like to process a series of french dates such as:

"lundi 20, mardi 21 mercredi 22 jeudi 23 vendredi 24 samedi 25 et dimanche 26 avril"

An equivalent in english would be:

"Monday 20, Tuesday 21 Wednesday 22 Thursday 23 Friday 24 Saturday 25 and Sunday, April
26"

where all the dates should apply ("be relative") to April.

I ended up writing the following rule:

RULENAME="date_r4d2",EXTRACTION="(%reWeekday %reDayNumber%reAndOrTo)+%reWeekday %reDayNumber
(%reMonthLong|%reMonthShort)",NORM_VALUE="UNDEF-year-%normMonth(group(7))-%normDay(group(3))",OFFSET="group(2)-group(3)"

Note: %reAndOrTo is ( et | ou | au |,\s|\s) in my case

And I get this result:

Monday, March 9, 2015 0:00
Tuesday, March 10, 2015 0:00
Wednesday, March 11, 2015 0:00
Thursday, March 12, 2015 0:00
Friday, March 13, 2015 0:00
Saturday, April 25, 2015 0:00
Sunday, April 26, 2015 0:00

The XML version:
<!DOCTYPE TimeML SYSTEM "TimeML.dtd">
<TimeML>
<TIMEX3 tid="t5" type="DATE" value="2015-03-09">lundi</TIMEX3> 20, <TIMEX3 tid="t6"
type="DATE" value="2015-03-10">mardi</TIMEX3> 21 <TIMEX3 tid="t7" type="DATE" value="2015-03-11">mercredi</TIMEX3>
22 <TIMEX3 tid="t8" type="DATE" value="2015-03-12">jeudi</TIMEX3> 23 <TIMEX3 tid="t9"
type="DATE" value="2015-03-13">vendredi</TIMEX3> 24 <TIMEX3 tid="t4" type="DATE" value="2015-04-25">samedi
25</TIMEX3> et <TIMEX3 tid="t3" type="DATE" value="2015-04-26">dimanche 26 avril</TIMEX3>
</TimeML>


As you can see, only the two last dates are correct.

The key here is that I have a repeatable group (%reWeekday %reDayNumber%reAndOrTo)+

I tried a lot of alternatives in my regular expression, like using a non-capturing
group as in \(hello\), etc.

Actually, I do not know if it is an OFFSET issue or if Heideltime is not able to handle
such regular expressions.
Do you have any clue that could help me ?

Thank you very much,

Pascal


```

Original issue reported on code.google.com by `pascalgill3t` on 2015-03-14 21:39:56

**Comment by pgillet** [comment]
Hi,

Did you add a fix for this issue?

Pascal

**Comment by jzell** [comment]
Hey, 

apologies for the long-delayed answer. We mixed up some signals in coordinating to handle the issue over at Google Code and never got around to looking at the automatically-imported report.

We never did anything to fix this issue because the logic behind it exceeds the capabilities of our rule language as well as the logic we have built into HeidelTime, and lastly, Java's regex engine.
First for a brief explanation on the normalization of the sentence
> lundi 20, mardi 21 mercredi 22 jeudi 23 vendredi 24 samedi 25 et dimanche 26 avril

normalizes to:

> Monday, March 9, 2015 0:00
> Tuesday, March 10, 2015 0:00
> Wednesday, March 11, 2015 0:00
> Thursday, March 12, 2015 0:00
> Friday, March 13, 2015 0:00
> Saturday, April 25, 2015 0:00
> Sunday, April 26, 2015 0:00

We get two correctly extracted and normalized expressions near the end because there exists a set of rules that can perfectly extract these expressions. The reason why the previous five expressions are normalized incorrectly is that the rule that *extracts* them is for underspecified expressions that don't contain any information about month or even year. In this case, HeidelTime computes the normalization date relative to previous expressions that it was able to normalize fully. In your particular case, you likely ran this back in March and used the domain NEWS (=> document creation time (DCT) is set to the current date), so it normalized these days to dates in March, whereas the last two have an explicit mentioning of the month.

Now for the rule you created. The regex is valid; by itself, a regex engine would be able to match your entire sentence. The problem is that while you can use multiplicity on groups to match repetitive text of arbitrary length, it's not possible to address these repetitive groups from the Java source code. That is to say, you may be able to extract something entirely like
> mardi 21 mercredi 22 jeudi 23

using just the extraction regex
> (%reWeekday %reDayNumber )+

in pure Java, but given the way HeidelTime and in particular Java's regex engine work, you would have no way of figuring out where one occurrence of `mardi 21` or `mercredi 22` starts or ends, and thus the normalization cannot be applied, as `+` doesn't give you an idea of how many groups to expect and literally means "between one and infinity occurrences".

Given all that, your only realistic chance of normalizing these would be to write pretty large rules that extract the entire expression. However, that becomes tedious really quickly as these expressions, as demonstrated by your example, can become arbitrarily long, and would require a LOT of compound rules (one to extract and normalize each single part of the list).

**Comment by pgillet** [comment]
You said that "HeidelTime computes the normalization date relative to previous expressions that it was able to normalize fully". In the example above, it would be Sunday, April 26, 2015.
How can I retrieve this date programmatically ?
Is it conceivable to re-inject the normalization date as the DCT, and to run Heideltime again (2nd pass): in this case, all the dates found are correct!

Thanks.

**Comment by JannikStroetgen** [comment]
In general, we have to distinguish between two cases:
using HeidelTime for processing news and using HeidelTime for processing narrative style documents.

If we are processing narratives and thus set the domain to "narratives", the DCT is never used for normalization purposes. Imagine "In March" in a Wikipedia article, then the DCT is not helpful to normalize this expression but the reference time has to be detected in the text.

If we are processing news-style documents, the DCT is often used for normalization. However, only if the normalization part of a rule starts with "UNDEF-..." and not with "UNDEF-REF".  The latter is used, for instance, to normalize expressions such as "the next month" - which typically refers to a month after the previously mentioned one independent of the DCT of a document.

I.e., if you want to use a previous expression as reference time, then the rule has to contain UNDEF-REF.

Hope this helps,
Jannik

**Comment by jzell** [comment]
> You said that "HeidelTime computes the normalization date relative to previous expressions that it was able to normalize fully". In the example above, it would be Sunday, April 26, 2015.

That's not quite correct. As I wrote in my original answer, to normalize expression <n>, HeidelTime will look for a fully normalized DATE expression that occurs *BEFORE* that expression, so n-1, n-2, ..., 0, and not the ones after that, which would then indeed have a correct month value of April as extracted by the rule that extracts expression of the form
> "[day-of-week] [day-of-month] et [day-of-week] [day-of-month] [month]"

.
> How can I retrieve this date programmatically ?
The scenario you're suggesting isn't really feasible with the current architecture. While the HeidelTimeStandalone class doesn't expose any extracted entities at all, but just outputs TimeML-formatted strings, building a UIMA pipeline from scratch like we do in that class might get you closer to your target in so far as you will be able to access a collection of TIMEX expressions programmatically. However, while we do expose whether a rule has extracted an explicit date ("June 5th 2014") or an implicit date ("January 3" with no year given), we don't expose a granularity that would let you differentiate between an implicit date where the day was given vs. one where day and month were given.

So your proposed way of "extracting" a DCT in a first pass and then using it in a second pass probably wouldn't produce better results for a vast majority of documents, particularly those with dates in two different months or years.
