### ISSUE TITLE
problem with the execution

### ISSUE THREAD

**Issue by fbehzadi** [HeidelTime/heideltime#36]
i am working on persian language of heideltime and wanna improve that.i am using standalone kit.i've improved resources,in first run in CMD,it has detected many temporal expressions,Of course i manually calculate recall and precision measure ,recall was 0.50 and precision was 0.98.
but in second time,it has found  less than first time.and it shows this error:

> java -Dfile.encoding=UTF-8 -jar de.unihd.dbs.heideltime.standalone.jar biographies.txt -l auto-persian -pos no
[RuleManager] Cannot read the following line of rule resource daterules
[RuleManager] Line: ﻿// author: Jannik Strötgen
[HeidelTime] HeidelTime's execution has been interrupted by an exception that is likely rooted in faulty normalization resource files. Please consider opening an issue report containing the following information at our GitHub project issue tracker: https://github.com/HeidelTime/heideltime/issues - Thanks!
java.lang.NullPointerException
        at java.lang.String.replace(Unknown Source)
        at de.unihd.dbs.uima.annotator.heideltime.HeidelTime.applyRuleFunctions(HeidelTime.java:2268)
        at de.unihd.dbs.uima.annotator.heideltime.HeidelTime.getAttributesForTimexFromFile(HeidelTime.java:2371)
        at de.unihd.dbs.uima.annotator.heideltime.HeidelTime.findTimexes(HeidelTime.java:2195)
        at de.unihd.dbs.uima.annotator.heideltime.HeidelTime.process(HeidelTime.java:223)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:497)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:443)
        at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.main(HeidelTimeStandalone.java:760)
[HeidelTime] Sentence [0-2384]: 

[HeidelTime] Language: auto-persian
[HeidelTime] Re-running this sentence with DEBUGGING enabled...
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(2))
 DEBUGGING: mr.group():%normYearBC(group(2))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():سال 1991
 DEBUGGING: m.group(2):1991
 DEBUGGING: hmR...:1991
 -----------------------------------
 t11EXTRACTION PHASE:    found by:date_lrec1b-explicit text:1991
 t11NORMALIZATION PHASE: found by:date_lrec1b-explicit text:1991 value:1991
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(2))
 DEBUGGING: mr.group():%normYearBC(group(2))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():سال 2011
 DEBUGGING: m.group(2):2011
 DEBUGGING: hmR...:2011
 -----------------------------------
 t12EXTRACTION PHASE:    found by:date_lrec1b-explicit text:2011
 t12NORMALIZATION PHASE: found by:date_lrec1b-explicit text:2011 value:2011
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(2))
 DEBUGGING: mr.group():%normYearBC(group(2))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():سال

2009
 DEBUGGING: m.group(2):2009
 DEBUGGING: hmR...:2009
 -----------------------------------
 t13EXTRACTION PHASE:    found by:date_lrec1b-explicit text:2009
 t13NORMALIZATION PHASE: found by:date_lrec1b-explicit text:2009 value:2009
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(2))
 DEBUGGING: mr.group():%normYearBC(group(2))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():سال 2009
 DEBUGGING: m.group(2):2009
 DEBUGGING: hmR...:2009
 -----------------------------------
 t14EXTRACTION PHASE:    found by:date_lrec1b-explicit text:2009
 t14NORMALIZATION PHASE: found by:date_lrec1b-explicit text:2009 value:2009
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(2))
 DEBUGGING: mr.group():%normYearBC(group(2))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():سال 91
 DEBUGGING: m.group(2):91
 DEBUGGING: hmR...:0091
 -----------------------------------
 t15EXTRACTION PHASE:    found by:date_lrec1b-explicit text:91
 t15NORMALIZATION PHASE: found by:date_lrec1b-explicit text:91 value:0091
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(3))
 DEBUGGING: mr.group():%normYearBC(group(3))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):3
 DEBUGGING: m.group():2009-12
 DEBUGGING: m.group(3):2009
 DEBUGGING: hmR...:2009
 -----------------------------------
 -----------------------------------
 DEBUGGING: tonormalize:%normApprox4Dates(group(2))
 DEBUGGING: mr.group():%normApprox4Dates(group(2))
 DEBUGGING: mr.group(1):normApprox4Dates
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():2009-12
 DEBUGGING: m.group(2):null
 DEBUGGING: hmR...:null
 -----------------------------------
 Empty part to normalize in normApprox4Dates
 t16EXTRACTION PHASE:    found by:date_lrec1e-explicit text:2009
 t16NORMALIZATION PHASE: found by:date_lrec1e-explicit text:2009 value:2009
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(3))
 DEBUGGING: mr.group():%normYearBC(group(3))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):3
 DEBUGGING: m.group():2009-12
 DEBUGGING: m.group(3):2009
 DEBUGGING: hmR...:2009
 -----------------------------------
 -----------------------------------
 DEBUGGING: tonormalize:%normApprox4Dates(group(2))
 DEBUGGING: mr.group():%normApprox4Dates(group(2))
 DEBUGGING: mr.group(1):normApprox4Dates
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():2009-12
 DEBUGGING: m.group(2):null
 DEBUGGING: hmR...:null
 -----------------------------------
 Empty part to normalize in normApprox4Dates
 t17EXTRACTION PHASE:    found by:date_lrec1e-explicit text:2009
 t17NORMALIZATION PHASE: found by:date_lrec1e-explicit text:2009 value:2009
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(3))
 DEBUGGING: mr.group():%normYearBC(group(3))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):3
 DEBUGGING: m.group():2010-01
 DEBUGGING: m.group(3):2010
 DEBUGGING: hmR...:2010
 -----------------------------------
 -----------------------------------
 DEBUGGING: tonormalize:%normApprox4Dates(group(2))
 DEBUGGING: mr.group():%normApprox4Dates(group(2))
 DEBUGGING: mr.group(1):normApprox4Dates
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():2010-01
 DEBUGGING: m.group(2):null
 DEBUGGING: hmR...:null
 -----------------------------------
 Empty part to normalize in normApprox4Dates
 t18EXTRACTION PHASE:    found by:date_lrec1e-explicit text:2010
 t18NORMALIZATION PHASE: found by:date_lrec1e-explicit text:2010 value:2010
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(3))
 DEBUGGING: mr.group():%normYearBC(group(3))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):3
 DEBUGGING: m.group():19-20
 DEBUGGING: m.group(3):19
 DEBUGGING: hmR...:0019
 -----------------------------------
 -----------------------------------
 DEBUGGING: tonormalize:%normApprox4Dates(group(2))
 DEBUGGING: mr.group():%normApprox4Dates(group(2))
 DEBUGGING: mr.group(1):normApprox4Dates
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():19-20
 DEBUGGING: m.group(2):null
 DEBUGGING: hmR...:null
 -----------------------------------
 Empty part to normalize in normApprox4Dates
 t19EXTRACTION PHASE:    found by:date_lrec1e-explicit text:19
 t19NORMALIZATION PHASE: found by:date_lrec1e-explicit text:19 value:0019
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(3))
 DEBUGGING: mr.group():%normYearBC(group(3))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):3
 DEBUGGING: m.group():1850-58
 DEBUGGING: m.group(3):1850
 DEBUGGING: hmR...:1850
 -----------------------------------
 -----------------------------------
 DEBUGGING: tonormalize:%normApprox4Dates(group(2))
 DEBUGGING: mr.group():%normApprox4Dates(group(2))
 DEBUGGING: mr.group(1):normApprox4Dates
 DEBUGGING: mr.group(2):2
 DEBUGGING: m.group():1850-58
 DEBUGGING: m.group(2):null
 DEBUGGING: hmR...:null
 -----------------------------------
 Empty part to normalize in normApprox4Dates
 t20EXTRACTION PHASE:    found by:date_lrec1e-explicit text:1850
 t20NORMALIZATION PHASE: found by:date_lrec1e-explicit text:1850 value:1850
 -----------------------------------
 DEBUGGING: tonormalize:%normYearBC(group(7))-%normMonth(group(1))
 DEBUGGING: mr.group():%normYearBC(group(7))
 DEBUGGING: mr.group(1):normYearBC
 DEBUGGING: mr.group(2):7
 DEBUGGING: m.group():نوامبر

19
 DEBUGGING: m.group(7):19
 DEBUGGING: hmR...:0019
 -----------------------------------
 -----------------------------------
 DEBUGGING: tonormalize:0019-%normMonth(group(1))
 DEBUGGING: mr.group():%normMonth(group(1))
 DEBUGGING: mr.group(1):normMonth
 DEBUGGING: mr.group(2):1
 DEBUGGING: m.group():نوامبر

19
 DEBUGGING: m.group(1):نوامبر
 DEBUGGING: hmR...:null
 -----------------------------------
 Maybe problem with normalization of the resource: normMonth
 Maybe problem with part to replace? نوامبر
[HeidelTime] Execution will now resume.
<?xml version="1.0"?>
<!DOCTYPE TimeML SYSTEM "TimeML.dtd">
<TimeML>

<TIMEX3 tid="t16" type="DATE" value="2009">2009</TIMEX3>-12-19,17:00:00

<TIMEX3 tid="t17" type="DATE" value="2009">2009</TIMEX3>-12-19 17:00:00

12/29/2000 20:29

<TIMEX3 tid="t18" type="DATE" value="2010">2010</TIMEX3>-01-29

1999/26/09

<TIMEX3 tid="t19" type="DATE" value="0019">19</TIMEX3>-20 از ماه نوامبر

فوریه سال <TIMEX3 tid="t11" type="DATE" value="1991">1991</TIMEX3>

می و ژوئن،2011

می-ژوئن 2011

تا ماه ژوئن سال <TIMEX3 tid="t12" type="DATE" value="2011">2011</TIMEX3>

<TIMEX3 tid="t13" type="DATE" value="2009">2009</TIMEX3>

از سال <TIMEX3 tid="t14" type="DATE" value="2009">2009</TIMEX3>

سال <TIMEX3 tid="t15" type="DATE" value="0091">91</TIMEX3>

<TIMEX3 tid="t20" type="DATE" value="1850">1850</TIMEX3>-58

</TimeML>

thank you so much.
fatemeh

**Comment by JannikStroetgen** [comment]
It seems like you have a bug in one of your rules (date_lrec1e-explicit ). 

DEBUGGING: tonormalize:%normApprox4Dates(group(2))
DEBUGGING: mr.group():%normApprox4Dates(group(2))
DEBUGGING: mr.group(1):normApprox4Dates
DEBUGGING: mr.group(2):2
DEBUGGING: m.group():1850-58
DEBUGGING: m.group(2):null
DEBUGGING: hmR...:null

Here, "group(2)" seems to match "2" and it is specified that group(2) should be normalized with normApprox4Dates - but normApprox4Dates does not contain "2"

If you can't find the bug, feel free to send us your rule file in which this rule occurs. We will try to check what's syntactically wrong in the rule then.

**Comment by fbehzadi** [comment]
Hello Jannik
I found previous bug.thank you.then I have another bug in it.i can't send
it from GitHub.would you mind please check it?
thank you so much.

Your sincerely
*Fateme Behzadi*

**Comment by fbehzadi** [comment]
Hello Jannik
I found previous bug.thank you.then I have another bug in it.i can't send
it from GitHub.would you mind please check your email?
thank you so much.

Your sincerely
*Fateme Behzadi*
