### ISSUE TITLE
next friday afternoon Problem

### ISSUE THREAD

**Issue by DongjunLee** [HeidelTime/heideltime#42]
Hi. 
heideltime is awesome. 

I have a little problem. 

- version : 2.1 standalone
- document type: News
- base time : 2016-10-19

i works good.
- input : next friday
- output : \<TIMEX3 tid="t1" type="DATE" value="2016-10-21">next friday</TIMEX3>

- input : friday afternoon
- output : \<TIMEX3 tid="t1" type="TIME" value="2016-10-15TAF">friday afternoon</TIMEX3>

but, 

- input : next friday afternoon
- output : next \<TIMEX3 tid="t1" type="TIME" value="2016-10-15TAF">friday afternoon</TIMEX3>

next is not tagging.

How can i tagging all together?
like, \<TIMEX3 tid="t1" type="DATETIME" value="2016-10-21TAF">next friday afternoon</TIMEX3>

**Comment by JannikStroetgen** [comment]
Hi,

Thanks for bringing this up. In general, the rule syntax of HeidelTime is not very difficult. Depending on your background you might want to try adding / changing some rules on your own. If you do so and want to share something, this would also be great of course

For this particular issue, we now added a rule to the English time rules it is something useful in general.

You can either do a "pull" from the master branch or if you use the released version of HeidelTime (UIMA or standalone), you can add the rule directly in your english/rules/resources_rules_timerules.txt file:
// EXAMPLE r3e: last Friday morning
RULENAME="time_r3e",EXTRACTION="%reThisNextLast %reWeekday %rePartOfDay",NORM_VALUE="UNDEF-%normThisNextLast(group(1))-%LOWERCASE%(group(2))T%normPartOfDay(group(3))"

Alternatively, just get the following file and replace it in your English rules folder:
https://github.com/HeidelTime/heideltime/blob/master/resources/english/rules/resources_rules_timerules.txt

Hope this helps. If you need further help or spot other things, feel free to let us know.

Cheers,
Jannik

**Comment by DongjunLee** [comment]
Thank you for your kindness. @JannikStroetgen  :)
It's very helpful.
