### ISSUE TITLE
Getting access to the logger of Heideltime

### ISSUE THREAD

**Issue by Nelly-Barret** [HeidelTime/heideltime#86]
Hi developers!

I'm using Heideltime in my project to extract dates from many texts. I'm currently working on a Java project which includes Heideltime as a Maven dependancy. Since my project has a lot of text files to analyse, the output that I get is very verbose. Indeed, for each text I got this piece of output:

```
Apr 08, 2021 9:05:35 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone initialize
INFO: HeidelTimeStandalone initialized with language english
Apr 08, 2021 9:05:35 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone readConfigFile
INFO: trying to read in file lib/heideltime/config-heideltime.props
Apr 08, 2021 9:05:37 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone initialize
INFO: HeidelTime initialized
Apr 08, 2021 9:05:37 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone initialize
INFO: JCas factory initialized
Apr 08, 2021 9:05:37 AM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone process
INFO: Processing started
```

When I run my project on more than tens of documents, you can easily imagine the  number of lines that my output got... (see my attached screenshot, and this is just the half of my output...)

<img width="1792" alt="Screenshot 2021-04-07 at 16 30 11" src="https://user-images.githubusercontent.com/34347677/113883589-94258780-97be-11eb-97dd-9b6e2a7b5c13.png">

**So my questions are:**

- Is there a way to **access the logger** that is defined in `de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.java` line 106 as a private field?
- **If not, is it possible for you to add a getter for this logger** (like ` Logger getLogger() { return this.logger; }`), such that we can manage the properties of the logger (mainly set the level of the output).

Finally, I would like to congratulate developers and authors to provide such a nice and easy-to-use tool! 🎉 

Thanks in advance for considering my question!

Nelly B.

**Comment by Nelly-Barret** [comment]
I found how to set the logger level to OFF: `LogManager.getLogManager().getLogger("HeidelTimeStandalone").setLevel(java.util.logging.Level.OFF);`.

In case this might help anybody.

**Comment by kenadianu** [comment]
A more specific example,

```
HeidelTimeStandalone heidelTime = new HeidelTimeStandalone();

java.util.logging.logger htLogger = java.utillogging.LogManager.getLogManager().getLogger("HeidelTimeStandalone");
htLogger.setLevel(java.util.logging.Level.OFF);

heidelTime = new HeidelTimeStandalone(Language.ENGLISH,DocumnetType.NARRATIVES,OutputType.TIMEML,"./config.props",POSTagger.NO);
```
